language: python

jobs:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8-dev
          dist: xenial
          sudo: true
        - os: osx
          language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --upgrade pip setuptools wheel; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install -U -e .[dev]; else pip install -U -e .[dev]; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 freeze; else pip freeze; fi

script:
    - coverage run --branch --source termtosvg -m unittest -v

after_success:
    - coverage report
    - pylint --extension-pkg-whitelist lxml termtosvg/*.py

notifications:
  email: false
